[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eb"
version = "0.1.0"
description = "EB - primitive line ebitor"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
	"prompt_toolkit>=3.0.0",
]

[project.scripts]
eb = "eb.eb:main"

[tool.setuptools.packages.find]
include = ["eb*"]
